import * as pgSchema from './schema-pg';
import * as sqliteSchema from './schema-sqlite';

const schema = process.env.POSTGRES_URL ? pgSchema : sqliteSchema;

export const documents = schema.documents;
export const serpCache = schema.serpCache;
export const analysisSnapshots = schema.analysisSnapshots;
export const users = schema.users;
export const projects = schema.projects;
export const projectMembers = schema.projectMembers;
export const skills = schema.skills;
export const projectAgentProfiles = schema.projectAgentProfiles;
export const agentSharedProfiles = schema.agentSharedProfiles;
export const skillParts = schema.skillParts;
export const aiProviders = schema.aiProviders;
export const aiModelConfig = schema.aiModelConfig;
export const documentComments = schema.documentComments;
export const invitations = schema.invitations;
export const keywords = schema.keywords;
export const keywordClusters = schema.keywordClusters;
export const keywordClusterMembers = schema.keywordClusterMembers;
export const sites = schema.sites;
export const gscPageDailyMetrics = schema.gscPageDailyMetrics;
export const pages = schema.pages;
export const siteDiscoveryUrls = schema.siteDiscoveryUrls;
export const crawlRuns = schema.crawlRuns;
export const crawlQueue = schema.crawlQueue;
export const pageSnapshots = schema.pageSnapshots;
export const pageArtifacts = schema.pageArtifacts;
export const pageArtifactJobs = schema.pageArtifactJobs;
export const pageIssues = schema.pageIssues;
export const documentPageLinks = schema.documentPageLinks;
export const taskPageLinks = schema.taskPageLinks;
export const pageKeywordMappings = schema.pageKeywordMappings;
export const auditLogs = schema.auditLogs;
export const alertEvents = schema.alertEvents;
