export const AI_SIGNATURE_WORDS: Set<string> = new Set([
  'delve', 'leverage', 'utilize', 'landscape', 'robust', 'comprehensive',
  'facilitate', 'moreover', 'furthermore', 'additionally', 'multifaceted',
  'holistic', 'synergy', 'paradigm', 'tapestry', 'nuanced', 'foster',
  'underscores', 'pivotal', 'poised', 'resonates', 'navigat',
]);

export const AI_TRANSITION_PHRASES: string[] = [
  'furthermore', 'moreover', 'additionally', 'in conclusion',
  "it's worth noting", 'it is important to note', 'notably',
  'conversely', 'consequently', "it's worth mentioning",
  'in addition to this', 'on the other hand', 'having said that',
  'with that being said', 'it is essential to',
];

export const AI_CLICHES: string[] = [
  'at the end of the day', 'a game-changer', 'the landscape of',
  'plays a crucial role', "in today's world", "in today's fast-paced",
  'navigate the complexities', 'a testament to', "it's worth mentioning",
  'shed light on', 'the realm of', 'stands as', 'cutting-edge',
  'deep dive', 'game changer', 'think outside the box', 'move the needle',
  'low-hanging fruit', 'circle back', 'touch base',
  'take it to the next level', 'at the forefront', 'pave the way',
  'in the ever-evolving', 'the intricacies of', 'a myriad of',
  'serves as a', 'is poised to', 'in this article', "whether you're a",
  'from seasoned', 'to beginners', 'in an era of',
  'it cannot be overstated',
];

export const FLUFF_ADVERBS: string[] = [
  'effectively', 'significantly', 'ultimately', 'essentially',
  'importantly', 'fundamentally', 'incredibly', 'relatively',
  'basically', 'certainly', 'clearly', 'obviously', 'definitely',
  'absolutely', 'particularly', 'generally', 'typically', 'simply',
  'merely', 'quite', 'rather', 'fairly', 'truly', 'highly',
  'extremely', 'remarkably', 'interestingly', 'undeniably',
  'undoubtedly', 'arguably',
];

export const PROMPT_LEAKAGE_PATTERNS: RegExp[] = [
  /^here are \d+/i,
  /^great question/i,
  /^that's a great/i,
  /^absolutely[!,.]/i,
  /^sure[!,.]/i,
  /^of course[!,.]/i,
  /^certainly[!,.]/i,
  /let me explain/i,
  /in this (article|guide|post|piece)/i,
  /whether you'?re a .+ or a/i,
  /^let's (dive|delve|explore|take a look)/i,
];

export const COLON_LEADINS: RegExp[] = [
  /the basic pitch:/i,
  /the short version:/i,
  /the (bottom|top) line:/i,
  /the takeaway:/i,
  /the (real|big|key|main) (question|issue|problem|point|takeaway|difference|reason|thing):/i,
  /here'?s (the thing|the deal|the catch|the kicker|the rub|what happened|what I (found|learned|noticed|realized)|why (that|this|it) matters|why I):/i,
  /translation:/i,
  /put (simply|differently|another way|bluntly):/i,
  /(in other|in plain|in simple) words:/i,
  /the (tl;?dr|tldr):/i,
  /spoiler( alert)?:/i,
  /quick (context|background|recap|note|aside|disclaimer):/i,
  /(one|a) (caveat|catch|note|word of (warning|caution|advice)|quick note|important note):/i,
  /(the )?verdict:/i,
  /(my|the) (honest )?(take|read|assessment|recommendation|advice):/i,
  /(pro tip|hot take|fun fact|side note|fair warning|full disclosure|worth noting):/i,
  /(the )?reality( is| check)?:/i,
  /(the )?context:/i,
  /(the )?upshot:/i,
  /long story short:/i,
  /big picture:/i,
  /(the )?tradeoff:/i,
  /(a |the )?word of (warning|caution):/i,
];

export const DEAD_METAPHORS: string[] = [
  'navigate the landscape', 'shed light on', 'the foundation of',
  'a driving force', 'tip of the iceberg', 'level the playing field',
  'raise the bar', 'push the envelope', 'break new ground',
  'a double-edged sword', 'a slippery slope', 'the elephant in the room',
  'at the heart of', 'the cornerstone of', 'a beacon of',
  'the fabric of', 'a pillar of', 'a window into', 'a bridge between',
  'the backbone of',
];

export const COMMON_WORDS: Set<string> = new Set([
  'the', 'be', 'to', 'of', 'and', 'a', 'in', 'that', 'have', 'i',
  'it', 'for', 'not', 'on', 'with', 'he', 'as', 'you', 'do', 'at',
  'this', 'but', 'his', 'by', 'from', 'they', 'we', 'say', 'her',
  'she', 'or', 'an', 'will', 'my', 'one', 'all', 'would', 'there',
  'their', 'what', 'so', 'up', 'out', 'if', 'about', 'who', 'get',
  'which', 'go', 'me', 'when', 'make', 'can', 'like', 'time', 'no',
  'just', 'him', 'know', 'take', 'people', 'into', 'year', 'your',
  'good', 'some', 'could', 'them', 'see', 'other', 'than', 'then',
  'now', 'look', 'only', 'come', 'its', 'over', 'think', 'also',
  'back', 'after', 'use', 'two', 'how', 'our', 'work', 'first',
  'well', 'way', 'even', 'new', 'want', 'because', 'any', 'these',
  'give', 'day', 'most', 'us', 'is', 'are', 'was', 'were', 'been',
  'being', 'has', 'had', 'did', 'does', 'doing', 'will', 'shall',
  'should', 'may', 'might', 'must', 'need', 'dare', 'ought', 'used',
  'am', 'let', 'made', 'find', 'here', 'thing', 'many', 'very',
  'still', 'own', 'through', 'mean', 'before', 'move', 'right',
  'boy', 'old', 'too', 'same', 'tell', 'does', 'set', 'three',
  'hand', 'high', 'keep', 'every', 'never', 'last', 'long', 'great',
  'little', 'own', 'other', 'old', 'right', 'big', 'even', 'such',
  'where', 'why', 'might', 'under', 'turn', 'again', 'off', 'play',
  'run', 'small', 'number', 'always', 'next', 'learn', 'world',
  'near', 'live', 'self', 'night', 'real', 'left', 'hard', 'part',
  'got', 'open', 'between', 'put', 'close', 'point', 'change',
  'kind', 'home', 'help', 'house', 'should', 'large', 'around',
  'end', 'along', 'each', 'much', 'show', 'every', 'began', 'head',
  'while', 'page', 'carry', 'took', 'water', 'earth', 'air', 'young',
  'name', 'place', 'man', 'live', 'spell', 'food', 'few', 'line',
  'read', 'add', 'land', 'girl', 'found', 'once', 'both', 'start',
  'went', 'done', 'something', 'stop', 'face', 'watch', 'seem',
  'together', 'talk', 'group', 'city', 'state', 'side', 'light',
  'call', 'often', 'enough', 'almost', 'idea', 'hear', 'far',
  'children', 'began', 'life', 'story', 'example', 'those', 'paper',
  'mile', 'feet', 'car', 'river', 'north', 'south', 'second',
  'late', 'above', 'form', 'important', 'until', 'sea', 'family',
  'music', 'body', 'color', 'question', 'mark', 'book', 'letter',
  'school', 'try', 'answer', 'grow', 'study', 'best', 'nothing',
  'need', 'love', 'write', 'mother', 'father', 'area', 'money',
  'serve', 'voice', 'power', 'door', 'problem', 'friend', 'room',
  'small', 'game', 'true', 'during', 'bring', 'word', 'age', 'unit',
  'able', 'ten', 'town', 'early', 'eye', 'dog', 'black', 'short',
  'white', 'sun', 'red', 'class', 'wind', 'sure', 'become', 'leave',
  'tree', 'cross', 'farm', 'hard', 'strong', 'draw', 'plan', 'free',
  'fish', 'green', 'sit', 'together', 'morning', 'table', 'war',
  'today', 'window', 'cover', 'half', 'rock', 'order', 'fire',
  'island', 'piece', 'across', 'cold', 'stood', 'top', 'whole',
  'king', 'street', 'inch', 'field', 'travel', 'clear', 'voice',
  'fall', 'hot', 'step', 'true', 'five', 'remember', 'horse',
  'base', 'hold', 'care', 'low', 'soon', 'less', 'front', 'feel',
  'fact', 'happen', 'gone', 'full', 'already', 'whose', 'behind',
  'pass', 'bed', 'product', 'rule', 'course', 'stay', 'blue',
  'deep', 'past', 'test', 'four', 'since', 'bottom', 'ball',
  'common', 'ground', 'build', 'figure', 'though', 'quite', 'among',
  'dark', 'gold', 'stood', 'ground', 'week', 'final', 'gave',
  'yet', 'fly', 'became', 'among', 'language', 'usually', 'certain',
  'girl', 'heart', 'ready', 'anything', 'woman', 'boy', 'rest',
  'minute', 'strong', 'produce', 'song', 'measure', 'plain',
  'itself', 'stand', 'contain', 'front', 'science', 'drive', 'stand',
  'full', 'hot', 'pull', 'return', 'free', 'force', 'note',
  'machine', 'check', 'huge', 'decide', 'perhaps', 'pick', 'act',
  'space', 'size', 'ran', 'round', 'boat', 'sleep', 'least',
  'direct', 'rain', 'appear', 'record', 'simple', 'mind', 'road',
  'interest', 'reach', 'fast', 'king', 'street', 'several', 'west',
  'wide', 'matter', 'cost', 'sort', 'stood', 'pair', 'six',
  'industry', 'edge', 'soft', 'age', 'fine', 'ten', 'possible',
  'hundred', 'north', 'south', 'half', 'past', 'children', 'team',
  'race', 'warm', 'pay', 'led', 'listen', 'single', 'toward',
  'major', 'hour', 'better', 'result', 'eight', 'human', 'provide',
  'class', 'woman', 'given', 'feel', 'system', 'art', 'seem',
  'present', 'main', 'land', 'east', 'company', 'wall', 'foot',
  'person', 'quite', 'whether', 'yes', 'clear', 'rather', 'bit',
  'press', 'close', 'night', 'main', 'lead', 'south', 'job',
  'thus', 'nor', 'rise', 'either', 'else', 'case', 'late',
  'piece', 'cut', 'quite', 'seem', 'least', 'stand', 'dark',
  'country', 'follow', 'came', 'ask', 'men', 'run', 'going',
  'number', 'course', 'sound', 'may', 'probably', 'water',
  'thought', 'shall', 'head', 'move', 'right', 'form', 'against',
  'look', 'knew', 'however', 'without', 'seen', 'must', 'part',
  'upon', 'point', 'turned', 'really', 'toward', 'white', 'away',
  'believe', 'idea', 'door', 'enough', 'ever', 'word', 'along',
  'hand', 'high', 'year', 'mother', 'light', 'country', 'father',
  'let', 'night', 'following', 'picture', 'being', 'study', 'second',
  'book', 'eye', 'job', 'play', 'held', 'later', 'miss', 'area',
  'government', 'business', 'issue', 'market', 'social', 'level',
  'local', 'report', 'member', 'law', 'program', 'making', 'position',
  'political', 'education', 'close', 'public', 'service', 'national',
  'information', 'control', 'history', 'deal', 'money', 'office',
  'court', 'place', 'general', 'process', 'reason', 'less', 'type',
  'effect', 'name', 'data', 'rate', 'support', 'role', 'model',
  'view', 'action', 'value', 'research', 'center', 'church',
  'report', 'building', 'table', 'period', 'student', 'board',
  'term', 'development', 'police', 'community', 'media', 'manager',
  'player', 'security', 'range', 'authority', 'skill', 'condition',
  'practice', 'form', 'land', 'whole', 'situation', 'policy',
  'economic', 'natural', 'experience', 'image', 'according', 'design',
  'tax', 'training', 'material', 'knowledge', 'list', 'evidence',
  'performance', 'staff', 'meeting', 'bank', 'director', 'technology',
  'management', 'plan', 'operation', 'test', 'strategy', 'activity',
  'club', 'investment', 'charge', 'cost', 'opportunity',
]);
